/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as AdmissionsStatusRouteImport } from './routes/admissions.status'
import { Route as AdmissionsApplyRouteImport } from './routes/admissions.apply'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedUploadResultsRouteImport } from './routes/_authenticated.upload-results'
import { Route as AuthenticatedTranscriptRouteImport } from './routes/_authenticated.transcript'
import { Route as AuthenticatedTeachingRouteImport } from './routes/_authenticated.teaching'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as AuthenticatedStandingRouteImport } from './routes/_authenticated.standing'
import { Route as AuthenticatedScopedResultsRouteImport } from './routes/_authenticated.scoped-results'
import { Route as AuthenticatedResultsArchiveRouteImport } from './routes/_authenticated.results-archive'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated.results'
import { Route as AuthenticatedResultCycleRouteImport } from './routes/_authenticated.result-cycle'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedRegistrationRouteImport } from './routes/_authenticated.registration'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedGraduationRouteImport } from './routes/_authenticated.graduation'
import { Route as AuthenticatedFirstLoginRouteImport } from './routes/_authenticated.first-login'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated.fees'
import { Route as AuthenticatedExamScheduleRouteImport } from './routes/_authenticated.exam-schedule'
import { Route as AuthenticatedExamOfficersRouteImport } from './routes/_authenticated.exam-officers'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated.departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated.courses'
import { Route as AuthenticatedBulkResultsRouteImport } from './routes/_authenticated.bulk-results'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated.audit-logs'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated.approvals'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated.apply'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated.applications'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated.announcements'
import { Route as AuthenticatedAllocationsRouteImport } from './routes/_authenticated.allocations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated.students.index'
import { Route as ApiPublicPasswordResetRequestRouteImport } from './routes/api/public/password-reset-request'
import { Route as ApiPublicMatricLoginInitRouteImport } from './routes/api/public/matric-login-init'
import { Route as AuthenticatedTranscriptsIdRouteImport } from './routes/_authenticated.transcripts.$id'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated.students.$id'
import { Route as AuthenticatedBroadsheetOfferingIdRouteImport } from './routes/_authenticated.broadsheet.$offeringId'
import { Route as AuthenticatedAdminImportIssLvt2022RouteImport } from './routes/_authenticated.admin.import-iss-lvt-2022'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsStatusRoute = AdmissionsStatusRouteImport.update({
  id: '/admissions/status',
  path: '/admissions/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplyRoute = AdmissionsApplyRouteImport.update({
  id: '/admissions/apply',
  path: '/admissions/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadResultsRoute =
  AuthenticatedUploadResultsRouteImport.update({
    id: '/upload-results',
    path: '/upload-results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTranscriptRoute = AuthenticatedTranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeachingRoute = AuthenticatedTeachingRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStandingRoute = AuthenticatedStandingRouteImport.update({
  id: '/standing',
  path: '/standing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScopedResultsRoute =
  AuthenticatedScopedResultsRouteImport.update({
    id: '/scoped-results',
    path: '/scoped-results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsArchiveRoute =
  AuthenticatedResultsArchiveRouteImport.update({
    id: '/results-archive',
    path: '/results-archive',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultCycleRoute =
  AuthenticatedResultCycleRouteImport.update({
    id: '/result-cycle',
    path: '/result-cycle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistrationRoute =
  AuthenticatedRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraduationRoute = AuthenticatedGraduationRouteImport.update({
  id: '/graduation',
  path: '/graduation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirstLoginRoute = AuthenticatedFirstLoginRouteImport.update({
  id: '/first-login',
  path: '/first-login',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamScheduleRoute =
  AuthenticatedExamScheduleRouteImport.update({
    id: '/exam-schedule',
    path: '/exam-schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamOfficersRoute =
  AuthenticatedExamOfficersRouteImport.update({
    id: '/exam-officers',
    path: '/exam-officers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBulkResultsRoute =
  AuthenticatedBulkResultsRouteImport.update({
    id: '/bulk-results',
    path: '/bulk-results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAllocationsRoute =
  AuthenticatedAllocationsRouteImport.update({
    id: '/allocations',
    path: '/allocations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const ApiPublicPasswordResetRequestRoute =
  ApiPublicPasswordResetRequestRouteImport.update({
    id: '/api/public/password-reset-request',
    path: '/api/public/password-reset-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMatricLoginInitRoute =
  ApiPublicMatricLoginInitRouteImport.update({
    id: '/api/public/matric-login-init',
    path: '/api/public/matric-login-init',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTranscriptsIdRoute =
  AuthenticatedTranscriptsIdRouteImport.update({
    id: '/transcripts/$id',
    path: '/transcripts/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedBroadsheetOfferingIdRoute =
  AuthenticatedBroadsheetOfferingIdRouteImport.update({
    id: '/broadsheet/$offeringId',
    path: '/broadsheet/$offeringId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminImportIssLvt2022Route =
  AuthenticatedAdminImportIssLvt2022RouteImport.update({
    id: '/import-iss-lvt-2022',
    path: '/import-iss-lvt-2022',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/allocations': typeof AuthenticatedAllocationsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/bulk-results': typeof AuthenticatedBulkResultsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/exam-officers': typeof AuthenticatedExamOfficersRoute
  '/exam-schedule': typeof AuthenticatedExamScheduleRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/first-login': typeof AuthenticatedFirstLoginRoute
  '/graduation': typeof AuthenticatedGraduationRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/registration': typeof AuthenticatedRegistrationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/result-cycle': typeof AuthenticatedResultCycleRoute
  '/results': typeof AuthenticatedResultsRoute
  '/results-archive': typeof AuthenticatedResultsArchiveRoute
  '/scoped-results': typeof AuthenticatedScopedResultsRoute
  '/standing': typeof AuthenticatedStandingRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teaching': typeof AuthenticatedTeachingRoute
  '/transcript': typeof AuthenticatedTranscriptRoute
  '/upload-results': typeof AuthenticatedUploadResultsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/admissions/status': typeof AdmissionsStatusRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/import-iss-lvt-2022': typeof AuthenticatedAdminImportIssLvt2022Route
  '/broadsheet/$offeringId': typeof AuthenticatedBroadsheetOfferingIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/transcripts/$id': typeof AuthenticatedTranscriptsIdRoute
  '/api/public/matric-login-init': typeof ApiPublicMatricLoginInitRoute
  '/api/public/password-reset-request': typeof ApiPublicPasswordResetRequestRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/allocations': typeof AuthenticatedAllocationsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/bulk-results': typeof AuthenticatedBulkResultsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/exam-officers': typeof AuthenticatedExamOfficersRoute
  '/exam-schedule': typeof AuthenticatedExamScheduleRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/first-login': typeof AuthenticatedFirstLoginRoute
  '/graduation': typeof AuthenticatedGraduationRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/registration': typeof AuthenticatedRegistrationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/result-cycle': typeof AuthenticatedResultCycleRoute
  '/results': typeof AuthenticatedResultsRoute
  '/results-archive': typeof AuthenticatedResultsArchiveRoute
  '/scoped-results': typeof AuthenticatedScopedResultsRoute
  '/standing': typeof AuthenticatedStandingRoute
  '/teaching': typeof AuthenticatedTeachingRoute
  '/transcript': typeof AuthenticatedTranscriptRoute
  '/upload-results': typeof AuthenticatedUploadResultsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/admissions/status': typeof AdmissionsStatusRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/import-iss-lvt-2022': typeof AuthenticatedAdminImportIssLvt2022Route
  '/broadsheet/$offeringId': typeof AuthenticatedBroadsheetOfferingIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/transcripts/$id': typeof AuthenticatedTranscriptsIdRoute
  '/api/public/matric-login-init': typeof ApiPublicMatricLoginInitRoute
  '/api/public/password-reset-request': typeof ApiPublicPasswordResetRequestRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/allocations': typeof AuthenticatedAllocationsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/bulk-results': typeof AuthenticatedBulkResultsRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/exam-officers': typeof AuthenticatedExamOfficersRoute
  '/_authenticated/exam-schedule': typeof AuthenticatedExamScheduleRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/first-login': typeof AuthenticatedFirstLoginRoute
  '/_authenticated/graduation': typeof AuthenticatedGraduationRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/registration': typeof AuthenticatedRegistrationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/result-cycle': typeof AuthenticatedResultCycleRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/results-archive': typeof AuthenticatedResultsArchiveRoute
  '/_authenticated/scoped-results': typeof AuthenticatedScopedResultsRoute
  '/_authenticated/standing': typeof AuthenticatedStandingRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/teaching': typeof AuthenticatedTeachingRoute
  '/_authenticated/transcript': typeof AuthenticatedTranscriptRoute
  '/_authenticated/upload-results': typeof AuthenticatedUploadResultsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/admissions/status': typeof AdmissionsStatusRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/import-iss-lvt-2022': typeof AuthenticatedAdminImportIssLvt2022Route
  '/_authenticated/broadsheet/$offeringId': typeof AuthenticatedBroadsheetOfferingIdRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/transcripts/$id': typeof AuthenticatedTranscriptsIdRoute
  '/api/public/matric-login-init': typeof ApiPublicMatricLoginInitRoute
  '/api/public/password-reset-request': typeof ApiPublicPasswordResetRequestRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/allocations'
    | '/announcements'
    | '/applications'
    | '/apply'
    | '/approvals'
    | '/audit-logs'
    | '/bulk-results'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/exam-officers'
    | '/exam-schedule'
    | '/fees'
    | '/first-login'
    | '/graduation'
    | '/profile'
    | '/registration'
    | '/reports'
    | '/result-cycle'
    | '/results'
    | '/results-archive'
    | '/scoped-results'
    | '/standing'
    | '/students'
    | '/teaching'
    | '/transcript'
    | '/upload-results'
    | '/users'
    | '/admissions/apply'
    | '/admissions/status'
    | '/admissions/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/import-iss-lvt-2022'
    | '/broadsheet/$offeringId'
    | '/students/$id'
    | '/transcripts/$id'
    | '/api/public/matric-login-init'
    | '/api/public/password-reset-request'
    | '/students/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/allocations'
    | '/announcements'
    | '/applications'
    | '/apply'
    | '/approvals'
    | '/audit-logs'
    | '/bulk-results'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/exam-officers'
    | '/exam-schedule'
    | '/fees'
    | '/first-login'
    | '/graduation'
    | '/profile'
    | '/registration'
    | '/reports'
    | '/result-cycle'
    | '/results'
    | '/results-archive'
    | '/scoped-results'
    | '/standing'
    | '/teaching'
    | '/transcript'
    | '/upload-results'
    | '/users'
    | '/admissions/apply'
    | '/admissions/status'
    | '/admissions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/import-iss-lvt-2022'
    | '/broadsheet/$offeringId'
    | '/students/$id'
    | '/transcripts/$id'
    | '/api/public/matric-login-init'
    | '/api/public/password-reset-request'
    | '/students'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/allocations'
    | '/_authenticated/announcements'
    | '/_authenticated/applications'
    | '/_authenticated/apply'
    | '/_authenticated/approvals'
    | '/_authenticated/audit-logs'
    | '/_authenticated/bulk-results'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/exam-officers'
    | '/_authenticated/exam-schedule'
    | '/_authenticated/fees'
    | '/_authenticated/first-login'
    | '/_authenticated/graduation'
    | '/_authenticated/profile'
    | '/_authenticated/registration'
    | '/_authenticated/reports'
    | '/_authenticated/result-cycle'
    | '/_authenticated/results'
    | '/_authenticated/results-archive'
    | '/_authenticated/scoped-results'
    | '/_authenticated/standing'
    | '/_authenticated/students'
    | '/_authenticated/teaching'
    | '/_authenticated/transcript'
    | '/_authenticated/upload-results'
    | '/_authenticated/users'
    | '/admissions/apply'
    | '/admissions/status'
    | '/admissions/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/import-iss-lvt-2022'
    | '/_authenticated/broadsheet/$offeringId'
    | '/_authenticated/students/$id'
    | '/_authenticated/transcripts/$id'
    | '/api/public/matric-login-init'
    | '/api/public/password-reset-request'
    | '/_authenticated/students/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdmissionsApplyRoute: typeof AdmissionsApplyRoute
  AdmissionsStatusRoute: typeof AdmissionsStatusRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMatricLoginInitRoute: typeof ApiPublicMatricLoginInitRoute
  ApiPublicPasswordResetRequestRoute: typeof ApiPublicPasswordResetRequestRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/status': {
      id: '/admissions/status'
      path: '/admissions/status'
      fullPath: '/admissions/status'
      preLoaderRoute: typeof AdmissionsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/apply': {
      id: '/admissions/apply'
      path: '/admissions/apply'
      fullPath: '/admissions/apply'
      preLoaderRoute: typeof AdmissionsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-results': {
      id: '/_authenticated/upload-results'
      path: '/upload-results'
      fullPath: '/upload-results'
      preLoaderRoute: typeof AuthenticatedUploadResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transcript': {
      id: '/_authenticated/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof AuthenticatedTranscriptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teaching': {
      id: '/_authenticated/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof AuthenticatedTeachingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/standing': {
      id: '/_authenticated/standing'
      path: '/standing'
      fullPath: '/standing'
      preLoaderRoute: typeof AuthenticatedStandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scoped-results': {
      id: '/_authenticated/scoped-results'
      path: '/scoped-results'
      fullPath: '/scoped-results'
      preLoaderRoute: typeof AuthenticatedScopedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results-archive': {
      id: '/_authenticated/results-archive'
      path: '/results-archive'
      fullPath: '/results-archive'
      preLoaderRoute: typeof AuthenticatedResultsArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/result-cycle': {
      id: '/_authenticated/result-cycle'
      path: '/result-cycle'
      fullPath: '/result-cycle'
      preLoaderRoute: typeof AuthenticatedResultCycleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registration': {
      id: '/_authenticated/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthenticatedRegistrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graduation': {
      id: '/_authenticated/graduation'
      path: '/graduation'
      fullPath: '/graduation'
      preLoaderRoute: typeof AuthenticatedGraduationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/first-login': {
      id: '/_authenticated/first-login'
      path: '/first-login'
      fullPath: '/first-login'
      preLoaderRoute: typeof AuthenticatedFirstLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-schedule': {
      id: '/_authenticated/exam-schedule'
      path: '/exam-schedule'
      fullPath: '/exam-schedule'
      preLoaderRoute: typeof AuthenticatedExamScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-officers': {
      id: '/_authenticated/exam-officers'
      path: '/exam-officers'
      fullPath: '/exam-officers'
      preLoaderRoute: typeof AuthenticatedExamOfficersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulk-results': {
      id: '/_authenticated/bulk-results'
      path: '/bulk-results'
      fullPath: '/bulk-results'
      preLoaderRoute: typeof AuthenticatedBulkResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/allocations': {
      id: '/_authenticated/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AuthenticatedAllocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/api/public/password-reset-request': {
      id: '/api/public/password-reset-request'
      path: '/api/public/password-reset-request'
      fullPath: '/api/public/password-reset-request'
      preLoaderRoute: typeof ApiPublicPasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/matric-login-init': {
      id: '/api/public/matric-login-init'
      path: '/api/public/matric-login-init'
      fullPath: '/api/public/matric-login-init'
      preLoaderRoute: typeof ApiPublicMatricLoginInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transcripts/$id': {
      id: '/_authenticated/transcripts/$id'
      path: '/transcripts/$id'
      fullPath: '/transcripts/$id'
      preLoaderRoute: typeof AuthenticatedTranscriptsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/broadsheet/$offeringId': {
      id: '/_authenticated/broadsheet/$offeringId'
      path: '/broadsheet/$offeringId'
      fullPath: '/broadsheet/$offeringId'
      preLoaderRoute: typeof AuthenticatedBroadsheetOfferingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/import-iss-lvt-2022': {
      id: '/_authenticated/admin/import-iss-lvt-2022'
      path: '/import-iss-lvt-2022'
      fullPath: '/admin/import-iss-lvt-2022'
      preLoaderRoute: typeof AuthenticatedAdminImportIssLvt2022RouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminImportIssLvt2022Route: typeof AuthenticatedAdminImportIssLvt2022Route
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminImportIssLvt2022Route:
    AuthenticatedAdminImportIssLvt2022Route,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAllocationsRoute: typeof AuthenticatedAllocationsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBulkResultsRoute: typeof AuthenticatedBulkResultsRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedExamOfficersRoute: typeof AuthenticatedExamOfficersRoute
  AuthenticatedExamScheduleRoute: typeof AuthenticatedExamScheduleRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedFirstLoginRoute: typeof AuthenticatedFirstLoginRoute
  AuthenticatedGraduationRoute: typeof AuthenticatedGraduationRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRegistrationRoute: typeof AuthenticatedRegistrationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResultCycleRoute: typeof AuthenticatedResultCycleRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedResultsArchiveRoute: typeof AuthenticatedResultsArchiveRoute
  AuthenticatedScopedResultsRoute: typeof AuthenticatedScopedResultsRoute
  AuthenticatedStandingRoute: typeof AuthenticatedStandingRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTeachingRoute: typeof AuthenticatedTeachingRoute
  AuthenticatedTranscriptRoute: typeof AuthenticatedTranscriptRoute
  AuthenticatedUploadResultsRoute: typeof AuthenticatedUploadResultsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedBroadsheetOfferingIdRoute: typeof AuthenticatedBroadsheetOfferingIdRoute
  AuthenticatedTranscriptsIdRoute: typeof AuthenticatedTranscriptsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAllocationsRoute: AuthenticatedAllocationsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedApplyRoute: AuthenticatedApplyRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBulkResultsRoute: AuthenticatedBulkResultsRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedExamOfficersRoute: AuthenticatedExamOfficersRoute,
  AuthenticatedExamScheduleRoute: AuthenticatedExamScheduleRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedFirstLoginRoute: AuthenticatedFirstLoginRoute,
  AuthenticatedGraduationRoute: AuthenticatedGraduationRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRegistrationRoute: AuthenticatedRegistrationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResultCycleRoute: AuthenticatedResultCycleRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedResultsArchiveRoute: AuthenticatedResultsArchiveRoute,
  AuthenticatedScopedResultsRoute: AuthenticatedScopedResultsRoute,
  AuthenticatedStandingRoute: AuthenticatedStandingRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTeachingRoute: AuthenticatedTeachingRoute,
  AuthenticatedTranscriptRoute: AuthenticatedTranscriptRoute,
  AuthenticatedUploadResultsRoute: AuthenticatedUploadResultsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedBroadsheetOfferingIdRoute:
    AuthenticatedBroadsheetOfferingIdRoute,
  AuthenticatedTranscriptsIdRoute: AuthenticatedTranscriptsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdmissionsApplyRoute: AdmissionsApplyRoute,
  AdmissionsStatusRoute: AdmissionsStatusRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMatricLoginInitRoute: ApiPublicMatricLoginInitRoute,
  ApiPublicPasswordResetRequestRoute: ApiPublicPasswordResetRequestRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
